

sync:
	"${MAKE}" -C d13.020 sync symfiles
	"${MAKE}" -C s13.020 sync symfiles

sortlink:
	"${MAKE}" -C d13.020 sortlink
	"${MAKE}" -C s13.020 sortlink

clean:
	"${MAKE}" -C d13.020 clean
	"${MAKE}" -C s13.020 clean
	